[programs.devnet]
myepicproject = "489pCidXNDXqYZvUwBX6okcPzXYzxCHPb8NDNTgzEpDT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/chetengkera/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
